//src/lib/constants.ts

export const indianStates = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const businessTypes = [
  "Retail",
  "Wholesale",
  "Distributor",
  "Manufacturing",
  "Service",
  "Others",
];

export const businessCategories = [
  "Accounting & CA",
  "Advertising & Marketing",
  "Agriculture",
  "Automotive",
  "Beauty & Personal Care",
  "Construction & Real Estate",
  "Consulting",
  "Education & Training",
  "Entertainment & Media",
  "Environmental Services",
  "Events & Hospitality",
  "Fashion & Apparel",
  "Finance & Insurance",
  "Fitness Center & Gym",
  "Food & Beverage",
  "Healthcare & Medical",
  "Home Services",
  "Interior Design",
  "IT & Technology",
  "Legal Services",
  "Logistics & Transportation",
  "Manufacturing (General)",
  "Non-Profit",
  "Pharmacy/Medical Store",
  "Photography & Videography",
  "Printing & Publishing",
  "Restaurant & Cafe",
  "Retail (General)",
  "Salon & Spa",
  "Security Services",
  "Sports & Recreation",
  "Travel & Tourism",
  "Wholesale (General)",
  "Others",
];
