//src/lib/constants.ts

export const businessTypes = [
  "Retail",
  "Wholesale",
  "Distributor",
  "Manufacturing",
  "Service",
  "Others",
] as const;

export const businessIndustries = [
  "Accounting & CA",
  "Advertising & Marketing",
  "Agriculture",
  "Automotive",
  "Beauty & Personal Care",
  "Construction & Real Estate",
  "Consulting",
  "Education & Training",
  "Entertainment & Media",
  "Environmental Services",
  "Events & Hospitality",
  "Fashion & Apparel",
  "Finance & Insurance",
  "Fitness Center & Gym",
  "Food & Beverage",
  "Healthcare & Medical",
  "Home Services",
  "Interior Design",
  "IT & Technology",
  "Legal Services",
  "Logistics & Transportation",
  "Manufacturing (General)",
  "Non-Profit",
  "Pharmacy/Medical Store",
  "Photography & Videography",
  "Printing & Publishing",
  "Restaurant & Cafe",
  "Retail (General)",
  "Salon & Spa",
  "Security Services",
  "Sports & Recreation",
  "Travel & Tourism",
  "Wholesale (General)",
  "Others",
] as const;
