import {
  InvoiceData,
  InvoiceSettings,
  PrintSettings,
} from "../_types/invoice.types";

export const defaultPrintSettings: PrintSettings = {
  // Header Settings
  showCompanyName: true,
  showCompanyLogo: true,
  showAddress: true,
  showEmail: true,
  showPhone: true,
  showGstin: true,
  repeatHeaderOnPages: true,

  // Paper Settings
  paperSize: "A4",
  companyNameSize: "medium",
  invoiceTextSize: "medium",
  printOriginalDuplicate: false,
  extraSpaceOnTop: 0,

  // Item Table
  minRowsInTable: 0,
  showHsnSac: true,
  showDiscount: true,
  showGst: true,

  // Totals & Taxes
  showTotalQuantity: true,
  showAmountWithDecimal: true,
  showReceivedAmount: true,
  showBalanceAmount: true,
  showCurrentBalance: true,
  showTaxDetails: true,
  showYouSaved: true,
  printAmountWithGrouping: true,
  amountInWordsFormat: "indian",

  // Footer
  showDescription: true,
  showTermsAndConditions: true,
  showSignature: true,
  signatureText: "Authorized Signatory",
  showPaymentMode: true,
  showBankDetails: true,
  showAcknowledgement: true,
  showAmountInWords: true,
};

export const defaultInvoiceSettings: InvoiceSettings = {
  templateId: "template1",
  primaryColor: "#0891b2",
  secondaryColor: "#06b6d4",
  fontFamily: "Inter",
  showTax: true,
  taxLabel: "GST",
  footerText: "Thank you for your business!",
  printSettings: defaultPrintSettings,
};

export const sampleInvoiceData: InvoiceData = {
  id: "1",
  invoiceNumber: "INV-101",
  issueDate: "2024-01-15",
  issueTime: "12:30 PM",
  dueDate: "2024-01-30",
  poDate: "2024-01-10",
  poNumber: "PO-2024-001",
  placeOfSupply: "Karnataka",
  status: "sent",
  company: {
    name: "Mondal Medicine",
    address: "Hooghly",
    city: "Kolkata",
    state: "West Bengal",
    zipCode: "712101",
    country: "India",
    phone: "7029929158",
    email: "contact@mondalmedicine.com",
    website: "www.mondalmedicine.com",
    taxId: "TAX-123456",
    gstin: "19ABCDE1234F1ZK",
  },
  customer: {
    name: "Classic Enterprises Pvt Ltd.",
    email: "classic@enterprises.com",
    phone: "8888888888",
    address: "Plot No. 1, Shop No. 8, Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560034",
    country: "India",
    gstin: "29VGVG7878V1ZS",
  },
  items: [
    {
      id: "1",
      description: "Crompton Rigged Ceiling Fan - Blue",
      hsnSac: "1452",
      quantity: 2,
      unitPrice: 1568.0,
      discount: 62.72,
      discountPercent: 2,
      gst: 5,
      total: 3275.94,
    },
    {
      id: "2",
      description: "Panasonic 10W LED Bulb",
      hsnSac: "8475",
      quantity: 6,
      unitPrice: 123.0,
      discount: 0,
      discountPercent: 0,
      gst: 3,
      total: 645.95,
    },
    {
      id: "3",
      description: "Sony BRAVIA 32 inch Android Smart TV",
      hsnSac: "4528",
      quantity: 1,
      unitPrice: 45000.0,
      discount: 2250.0,
      discountPercent: 5,
      gst: 12,
      total: 47880.0,
    },
    {
      id: "4",
      description: "Samsung Galaxy Buds Pro",
      hsnSac: "8518",
      quantity: 3,
      unitPrice: 8999.0,
      discount: 899.9,
      discountPercent: 10,
      gst: 18,
      total: 28516.41,
    },
  ],
  notes: "Sale Description",
  subtotal: 93751.0,
  discountTotal: 3212.62,
  taxRate: 12,
  taxAmount: 10702.11,
  totalAmount: 102452.0,
  receivedAmount: 50000.0,
  balanceAmount: 52452.0,
  paymentMode: "HDFC BANK - Whitefield branch (Trans18jVgf)",
  description: "Sale Description",
  termsAndConditions: "Thanks for doing business with us!",
  bankDetails: {
    bankName: "ICICI BANK",
    accountNumber: "1234567890",
    ifscCode: "IFSC000123",
    branch: "HSR LAYOUT",
  },
  transportDetails: {
    transportName: "ARVION Interstate Transport Service",
    vehicleNumber: "KA BA8A 7878",
    deliveryDate: "2024-01-20",
  },
};
